### ISSUE TITLE
In-App with credit not working

### ISSUE THREAD

**Issue by megasoft78** [Aptoide/appcoins-wallet-android#110]
Hi,
I tried to do an in-app when I have some credit but not enough for the in-app.
The first time I get "On purchase failed called with product" and the second one it close the game.

I tried with old and new sdk (Unity) and I'm getting the same behaviours.
AppCoins Wallet is the last one.

**Comment by Trinkes** [comment]
Hi @megasoft78,
What's your wallet and sdk versions?
what's the currency you have? AppCoins?
can you tell us the steps you are doing to help us reproduce the problem?

**Comment by megasoft78** [comment]
Hi,
AppCoins Wallet is version 1.2.9.14 and my SDK is BDS Unity Plugin v1.0.2 with Unity 2018.2.13f1.

I tested again and it doesn't happen. I don't know how to reproduce it again.
I'm sorry. :(

**Comment by Trinkes** [comment]
That's ok. 
I'll close this issue, if you have any update just reopen it.
