### ISSUE TITLE
Wallet blocked if the transaction get stuck

### ISSUE THREAD

**Issue by megasoft78** [Aptoide/appcoins-wallet-android#111]
Hi,
I'm experience issues on some wallets.
It seems that if a transaction get stuck you are not able to do that transaction anymore.
It's like stuck. I tried with latest version and I'm getting the same issue.
It wait forever with the message :
Details checked
Receiving your item...

Could you please help me?

I can't keep creating new wallets every time it get stuck. :(

**Comment by Trinkes** [comment]
Hey @megasoft78 ,
can you describe the steps in order to help us to reproduce your problem?
What's your wallet and sdk version?

**Comment by megasoft78** [comment]
Hi,
AppCoins Wallet is version 1.2.9.14 and my SDK is BDS Unity Plugin v1.0.2 with Unity 2018.2.13f1.

This happen all the time on different wallets.
I just open my game and click on in-app and click buy. It show me Transaction in progress and this screen stay this way forever.
I give up after about 15-20 minutes. I remember it should take about 2 minutes right?
I have APPC and ETH in my wallet.
The message says:
Details checked
Receiving you item...

I don't have other information.

**Comment by Trinkes** [comment]
Can you check if u have a purchase already?
For that just force stop the wallet reopen your app an after "OnInit" method check if you get the purchase

**Comment by megasoft78** [comment]
I already tried everything. I even reboot my phone to be 100% sure nothing is running but I still get the same message.
It doesn't show me the button Buy, it just start with this Transaction in Progress.

**Comment by Trinkes** [comment]
Can you share an apk where we can reproduce your problem?

**Comment by megasoft78** [comment]
Hi,
the apk is the one on aptoide Word Jungle.
It doesn't happen with every wallet. It happen only with some wallets when they get stuck.

**Comment by Trinkes** [comment]
can you provide the last 4 digits of the last stuck account wallet?

**Comment by megasoft78** [comment]
Sure,
last 4 letters in the stuck wallet address are : ae27

**Comment by Trinkes** [comment]
Is that wallet still stuck?

**Comment by megasoft78** [comment]
Now when I click to purchase I'm getting this crash:

`11-08 17:20:36.722 24392 24858 D HTTP_TRACE: <---------------------------BEGIN REQUEST---------------------------------->
11-08 17:20:36.722 24392 24858 D HTTP_TRACE: Request encoded url: GET https://api.blockchainds.com/broker/8.20180518/transactions?wallet.address=0x47e41a77584a828e37dC0466a6EfA75A2EB4aE27&wallet.signature=96a83774c03d9fd51b66968505a8ef4816f54638f3413d11a0115bd962dcc47e1ce9b1a585ec900061eaec123087594091a99fe12f0b593df773beadd074175301&cursor=0&type=INAPP&limit=1&sort.name=latest&sort.reverse=false&product=it.megasoft78.wordsjungle.small_pack_coins&domain=it.megasoft78.wordsjungle
11-08 17:20:36.722 24392 24858 D HTTP_TRACE: Request decoded url: GET https://api.blockchainds.com/broker/8.20180518/transactions?wallet.address=0x47e41a77584a828e37dC0466a6EfA75A2EB4aE27&wallet.signature=96a83774c03d9fd51b66968505a8ef4816f54638f3413d11a0115bd962dcc47e1ce9b1a585ec900061eaec123087594091a99fe12f0b593df773beadd074175301&cursor=0&type=INAPP&limit=1&sort.name=latest&sort.reverse=false&product=it.megasoft78.wordsjungle.small_pack_coins&domain=it.megasoft78.wordsjungle
11-08 17:20:36.722 24392 24858 D HTTP_TRACE: =============== Headers ===============
11-08 17:20:36.722 24392 24858 D HTTP_TRACE:
11-08 17:20:36.722 24392 24858 D HTTP_TRACE: =============== END Headers ===============
11-08 17:20:36.722 24392 24858 D HTTP_TRACE:
11-08 17:20:36.722 24392 24858 D HTTP_TRACE: Response timeout: 117ms
11-08 17:20:36.722 24392 24858 D HTTP_TRACE: Response message:
11-08 17:20:36.722 24392 24858 D HTTP_TRACE: Response code: 200
11-08 17:20:36.722 24392 24858 D HTTP_TRACE: Response body:
11-08 17:20:36.722 24392 24858 D HTTP_TRACE: {"next":"https:\/\/api.blockchainds.com\/broker\/8.20180518\/transactions?cursor=1","items":[{"uid":"wbSLjpPO_fj4ApcG","status":"PENDING_SERVICE_AUTHORIZATION","gateway":{"name":"adyen"}}]}
11-08 17:20:36.722 24392 24858 D HTTP_TRACE: =============== Headers ===============
11-08 17:20:36.722 24392 24858 D HTTP_TRACE: server : nginx/1.10.3 (Ubuntu)
11-08 17:20:36.722 24392 24858 D HTTP_TRACE: content-type : application/json
11-08 17:20:36.722 24392 24858 D HTTP_TRACE: date : Thu, 08 Nov 2018 16:20:36 GMT
11-08 17:20:36.722 24392 24858 D HTTP_TRACE:
11-08 17:20:36.722 24392 24858 D HTTP_TRACE: =============== END Headers ===============
11-08 17:20:36.722 24392 24858 D HTTP_TRACE:
11-08 17:20:36.722 24392 24858 D HTTP_TRACE: <-----------------------------END REQUEST--------------------------------->
11-08 17:20:36.722 24392 24858 D HTTP_TRACE:
11-08 17:20:36.722 24392 24858 D HTTP_TRACE:
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: <---------------------------BEGIN REQUEST---------------------------------->
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: Request encoded url: GET https://api.trustwalletapp.com/prices?currency=USD&&symbols=ETH
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: Request decoded url: GET https://api.trustwalletapp.com/prices?currency=USD&&symbols=ETH
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: =============== Headers ===============
11-08 17:20:36.930 24392 24440 D HTTP_TRACE:
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: =============== END Headers ===============
11-08 17:20:36.930 24392 24440 D HTTP_TRACE:
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: Response timeout: 271ms
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: Response message:
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: Response code: 200
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: Response body:
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: {"status":true,"response":[{"id":"ethereum","name":"Ethereum","symbol":"ETH","price":"213.092318431","percent_change_24h":"-2.08","image":"https://files.coinmarketcap.com/static/img/coins/128x128/ethereum.png"}]}
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: =============== Headers ===============
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: cf-ray : 47695e3129ae3d7d-MXP
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: server : cloudflare
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: expect-ct : max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: via : 1.1 vegur
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: vary : Accept-Encoding
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: etag : W/"d4-FveGx2Aqgt/stODH7JdqaFcoZZ0"
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: access-control-allow-origin : *
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: x-powered-by : Express
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: set-cookie : __cfduid=d6ca3dffe9fd2a0ead8b493212f496b251541694036; expires=Fri, 08-Nov-19 16:20:36 GMT; path=/; domain=.trustwalletapp.com; HttpOnly; Secure
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: content-type : application/json; charset=utf-8
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: date : Thu, 08 Nov 2018 16:20:36 GMT
11-08 17:20:36.930 24392 24440 D HTTP_TRACE:
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: =============== END Headers ===============
11-08 17:20:36.930 24392 24440 D HTTP_TRACE:
11-08 17:20:36.930 24392 24440 D HTTP_TRACE: <-----------------------------END REQUEST--------------------------------->
11-08 17:20:36.930 24392 24440 D HTTP_TRACE:
11-08 17:20:36.930 24392 24440 D HTTP_TRACE:
11-08 17:20:36.937 24392 24392 W System.err: java.lang.RuntimeException: io.reactivex.exceptions.OnErrorNotImplementedException: Cannot resume from PAUSED_CC_PAYMENT status
11-08 17:20:36.938 24392 24392 W System.err:    at com.asfoundation.wallet.App.lambda$setupRxJava$3(App.java:116)
11-08 17:20:36.938 24392 24392 W System.err:    at com.asfoundation.wallet.-$$Lambda$App$jbJJC5ZrE1AO-GbmxmR7s63ueIE.accept(Unknown Source:2)
11-08 17:20:36.938 24392 24392 W System.err:    at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:373)
11-08 17:20:36.938 24392 24392 W System.err:    at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:51)
11-08 17:20:36.938 24392 24392 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
11-08 17:20:36.938 24392 24392 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
11-08 17:20:36.938 24392 24392 W System.err:    at io.reactivex.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:73)
11-08 17:20:36.938 24392 24392 W System.err:    at io.reactivex.internal.operators.completable.CompletableError.subscribeActual(CompletableError.java:29)
11-08 17:20:36.938 24392 24392 W System.err:    at io.reactivex.Completable.subscribe(Completable.java:2171)
11-08 17:20:36.938 24392 24392 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91)
11-08 17:20:36.938 24392 24392 W System.err:    at io.reactivex.internal.operators.single.SingleZipArray$ZipCoordinator.innerSuccess(SingleZipArray.java:121)
11-08 17:20:36.938 24392 24392 W System.err:    at io.reactivex.internal.operators.single.SingleZipArray$ZipSingleObserver.onSuccess(SingleZipArray.java:172)
11-08 17:20:36.938 24392 24392 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
11-08 17:20:36.938 24392 24392 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
11-08 17:20:36.938 24392 24392 W System.err:    at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
11-08 17:20:36.939 24392 24392 W System.err:    at io.reactivex.Single.subscribe(Single.java:3394)
11-08 17:20:36.939 24392 24392 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
11-08 17:20:36.939 24392 24392 W System.err:    at io.reactivex.internal.operators.single.SingleZipArray$ZipCoordinator.innerSuccess(SingleZipArray.java:121)
11-08 17:20:36.939 24392 24392 W System.err:    at io.reactivex.internal.operators.single.SingleZipArray$ZipSingleObserver.onSuccess(SingleZipArray.java:172)
11-08 17:20:36.939 24392 24392 W System.err:    at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
11-08 17:20:36.939 24392 24392 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
11-08 17:20:36.939 24392 24392 W System.err:    at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
11-08 17:20:36.939 24392 24392 W System.err:    at io.reactivex.Single.subscribe(Single.java:3394)
11-08 17:20:36.939 24392 24392 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
11-08 17:20:36.939 24392 24392 W System.err:    at io.reactivex.internal.operators.observable.ObservableElementAtSingle$ElementAtObserver.onNext(ObservableElementAtSingle.java:91)
11-08 17:20:36.939 24392 24392 W System.err:    at io.reactivex.internal.operators.mixed.SingleFlatMapObservable$FlatMapObserver.onNext(SingleFlatMapObservable.java:69)
11-08 17:20:36.939 24392 24392 W System.err:    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
11-08 17:20:36.939 24392 24392 W System.err:    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
11-08 17:20:36.939 24392 24392 W System.err:    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
11-08 17:20:36.939 24392 24392 W System.err:    at android.os.Handler.handleCallback(Handler.java:790)
11-08 17:20:36.940 24392 24392 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
11-08 17:20:36.940 24392 24392 W System.err:    at android.os.Looper.loop(Looper.java:164)
11-08 17:20:36.940 24392 24392 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6494)
11-08 17:20:36.940 24392 24392 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
11-08 17:20:36.940 24392 24392 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
11-08 17:20:36.940 24392 24392 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
11-08 17:20:36.941 24392 24392 W System.err: Caused by: io.reactivex.exceptions.OnErrorNotImplementedException: Cannot resume from PAUSED_CC_PAYMENT status
11-08 17:20:36.941 24392 24392 W System.err:    ... 33 more
11-08 17:20:36.941 24392 24392 W System.err: Caused by: java.lang.UnsupportedOperationException: Cannot resume from PAUSED_CC_PAYMENT status
11-08 17:20:36.941 24392 24392 W System.err:    at com.asfoundation.wallet.ui.iab.OnChainBuyPresenter.lambda$null$13(OnChainBuyPresenter.java:155)
11-08 17:20:36.941 24392 24392 W System.err:    at com.asfoundation.wallet.ui.iab.-$$Lambda$OnChainBuyPresenter$-J_hj-0lVgORF34_7Ok_9y3nSrM.apply(Unknown Source:15)
11-08 17:20:36.941 24392 24392 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:83)
11-08 17:20:36.941 24392 24392 W System.err:    ... 26 more
11-08 17:20:37.173 24392 24828 I zygote  : Deoptimizing org.spongycastle.math.ec.ECPoint org.spongycastle.math.ec.FixedPointCombMultiplier.multiplyPositive(org.spongycastle.math.ec.ECPoint, java.math.BigInteger) due to JIT inline cache
11-08 17:20:37.245 24392 24403 I zygote  : Background concurrent copying GC freed 256656(23MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 20MB/41MB, paused 213us total 304.351ms
11-08 17:20:37.316   452  7059 W ActivityManager:   Force finishing activity com.appcoins.wallet/com.asfoundation.wallet.ui.iab.IabActivity
11-08 17:20:37.318   452  7059 E LightsService: Light requested not available on this device. 2
11-08 17:20:37.329   452  7059 W ActivityManager:   Force finishing activity com.appcoins.wallet/com.asfoundation.wallet.ui.Erc681Receiver
11-08 17:20:37.365 24392 24392 I Process : Sending signal. PID: 24392 SIG: 9
11-08 17:20:37.403   452  1174 I ActivityManager: Process com.appcoins.wallet (pid 24392) has died: fore TOP
11-08 17:20:37.403 24640 24640 D IabHelper: Billing service disconnected.
11-08 17:20:37.404   452  1174 W ActivityManager: Scheduling restart of crashed service com.appcoins.wallet/.billing.BillingService in 1000ms
11-08 17:20:37.404   452  7058 I WindowManager: WIN DEATH: Window{a6f542a u0 com.appcoins.wallet/com.asfoundation.wallet.ui.Erc681Receiver}
11-08 17:20:37.404   452   470 W zygote  : kill(-24392, 9) failed: No such process
11-08 17:20:37.408   452   544 W InputDispatcher: channel '1ededd0 com.appcoins.wallet/com.asfoundation.wallet.ui.iab.IabActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-08 17:20:37.409   452   544 E InputDispatcher: channel '1ededd0 com.appcoins.wallet/com.asfoundation.wallet.ui.iab.IabActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-08 17:20:37.424   452   763 I WindowManager: WIN DEATH: Window{1ededd0 u0 com.appcoins.wallet/com.asfoundation.wallet.ui.iab.IabActivity}
11-08 17:20:37.424   452   763 W InputDispatcher: Attempted to unregister already unregistered input channel '1ededd0 com.appcoins.wallet/com.asfoundation.wallet.ui.iab.IabActivity (server)'
11-08 17:20:37.440   452   470 W zygote  : kill(-24392, 9) failed: No such process
11-08 17:20:37.440   452   470 I zygote  : Successfully killed process cgroup uid 10212 pid 24392 in 35ms
11-08 17:20:37.449 24640 24640 D PurchaseActivity: onActivityResult with reqCode 10001 resultCode 0 and data null
11-08 17:20:37.449 24640 24640 D IabHelper: Ending async operation: launchPurchaseFlow
11-08 17:20:37.449 24640 24640 D IabHelper: Purchase canceled - Response: 6:Error
11-08 17:20:37.449 24640 24640 D PurchaseActivity: Purchase finished: IabResult: User canceled. (response: -1005:User cancelled), purchase: null
11-08 17:20:37.449 24640 24640 E PurchaseActivity: **** Unity BDS error: Error purchasing: IabResult: User canceled. (response: -1005:User cancelled)
11-08 17:20:37.464 24640 24640 D PurchaseActivity: onActivityResult handled by IABUtil.
11-08 17:20:37.464   452   715 W ActivityManager: Duplicate finish request for ActivityRecord{b0882b u0 it.megasoft78.wordsjungle/com.aptoide.appcoinsunity.PurchaseActivity t938 f}
11-08 17:20:37.465   452   477 W ActivityManager: setHasOverlayUi called on unknown pid: 24392
11-08 17:20:37.487 24640 24640 V GamesNativeSDK: Received Activity Resume Event.
11-08 17:20:37.496   619   640 W asset   : Asset path /data/app/com.mcprohosting.beam-PPZ2IhyVBwaCcVm2rhNVtA==/base.apk is neither a directory nor file (type=1).
11-08 17:20:37.496   619   640 E ResourcesManager: failed to add asset path /data/app/com.mcprohosting.beam-PPZ2IhyVBwaCcVm2rhNVtA==/base.apk
11-08 17:20:37.496   619   640 W PackageManager: Failure retrieving resources for com.mcprohosting.beam
11-08 17:20:37.497   619   640 W asset   : Asset path /data/app/com.mcprohosting.beam-PPZ2IhyVBwaCcVm2rhNVtA==/base.apk is neither a directory nor file (type=1).
11-08 17:20:37.497   619   640 E ResourcesManager: failed to add asset path /data/app/com.mcprohosting.beam-PPZ2IhyVBwaCcVm2rhNVtA==/base.apk
11-08 17:20:37.497   619   640 W PackageManager: Failure retrieving resources for com.mcprohosting.beam
11-08 17:20:37.497   619   640 W asset   : Asset path /data/app/com.mcprohosting.beam-PPZ2IhyVBwaCcVm2rhNVtA==/base.apk is neither a directory nor file (type=1).
11-08 17:20:37.497   619   640 E ResourcesManager: failed to add asset path /data/app/com.mcprohosting.beam-PPZ2IhyVBwaCcVm2rhNVtA==/base.apk
11-08 17:20:37.497   619   640 W PackageManager: Failure retrieving resources for com.mcprohosting.beam
11-08 17:20:37.536   259  2142 D ACDB-LOADER: ACDB -> send_afe_cal
11-08 17:20:37.536   259  2142 D audio_hw_primary: enable_snd_device: snd_device(2: speaker)
11-08 17:20:37.536   259  2142 D audio_route: Apply path: speaker
11-08 17:20:37.539 24640 24640 V MediaRouter: onRestoreRoute() : route=RouteInfo{ name=Tablet, description=null, status=null, category=RouteCategory{ name=Sistema types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
11-08 17:20:37.539 24640 24640 V MediaRouter: Selecting route: RouteInfo{ name=Tablet, description=null, status=null, category=RouteCategory{ name=Sistema types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
11-08 17:20:37.546   259  2142 D audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback
11-08 17:20:37.546   259  2142 D audio_route: Apply path: low-latency-playback
11-08 17:20:37.548   259   364 W AudioFlinger: checkEffectCompatibility_l(): non HW effect Equalizer on playback thread in fast mode
11-08 17:20:37.548  1071  2114 E AudioEffect: set(): AudioFlinger could not create effect 0bed4300-ddd6-11db-8f34-0002a5d5c51b / ec7178ec-e5e1-4432-a3f4-4657e6795210, status: -22
11-08 17:20:37.548  1071  2114 E AudioEffects-JNI: AudioEffect initCheck failed -3
11-08 17:20:37.548  1071  2114 E AudioEffect-JAVA: Error code -3 when initializing AudioEffect.
11-08 17:20:37.549  1071  2114 E AudioFx-EffectSet: error creatingEffectSet (AndroidEffects) [  mSessionId: 73 mDeviceInfo: android.media.AudioDeviceInfo@6964d3e mGlobalEnabled: false ], releasing and throwing!
11-08 17:20:37.549  1071  2114 E AudioFxService: couldn't create effects for session id: 73
11-08 17:20:37.549  1071  2114 E AudioFxService: java.lang.RuntimeException: Cannot initialize effect engine for type: 0bed4300-ddd6-11db-8f34-0002a5d5c51b Error: -3
11-08 17:20:37.549  1071  2114 E AudioFxService:        at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:411)
11-08 17:20:37.549  1071  2114 E AudioFxService:        at android.media.audiofx.Equalizer.<init>(Equalizer.java:139)
11-08 17:20:37.549  1071  2114 E AudioFxService:        at org.lineageos.audiofx.backends.EffectSetWithAndroidEq.onCreate(EffectSetWithAndroidEq.java:39)
11-08 17:20:37.549  1071  2114 E AudioFxService:        at org.lineageos.audiofx.backends.AndroidEffects.onCreate(AndroidEffects.java:53)
11-08 17:20:37.549  1071  2114 E AudioFxService:        at org.lineageos.audiofx.backends.EffectSet.<init>(EffectSet.java:41)
11-08 17:20:37.549  1071  2114 E AudioFxService:        at org.lineageos.audiofx.backends.EffectSetWithAndroidEq.<init>(EffectSetWithAndroidEq.java:34)
11-08 17:20:37.549  1071  2114 E AudioFxService:        at org.lineageos.audiofx.backends.AndroidEffects.<init>(AndroidEffects.java:48)
11-08 17:20:37.549  1071  2114 E AudioFxService:        at org.lineageos.audiofx.backends.EffectsFactory.createEffectSet(EffectsFactory.java:22)
11-08 17:20:37.549  1071  2114 E AudioFxService:        at org.lineageos.audiofx.service.SessionManager$AudioServiceHandler.handleMessage(SessionManager.java:320)
11-08 17:20:37.549  1071  2114 E AudioFxService:        at android.os.Handler.dispatchMessage(Handler.java:102)
11-08 17:20:37.549  1071  2114 E AudioFxService:        at android.os.Looper.loop(Looper.java:164)
11-08 17:20:37.549  1071  2114 E AudioFxService:        at android.os.HandlerThread.run(HandlerThread.java:65)
11-08 17:20:37.552 24640 24662 I Unity   : Purchase failed with error User canceled. (response: -1005:User cancelled)
11-08 17:20:37.552 24640 24662 I Unity   :
11-08 17:20:37.552 24640 24662 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-08 17:20:37.552 24640 24662 I Unity   :
11-08 17:20:37.563 24640 24662 I Unity   : On purchase failed called with product:
11-08 17:20:37.563 24640 24662 I Unity   :  skuID: it.megasoft78.wordsjungle.small_pack_coins
11-08 17:20:37.563 24640 24662 I Unity   :  type: Consumable
11-08 17:20:37.563 24640 24662 I Unity   :
11-08 17:20:37.563 24640 24662 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-08 17:20:37.563 24640 24662 I Unity   :
11-08 17:20:37.565 24640 24662 I Unity   : OnPurchaseFailed: FAIL.
11-08 17:20:37.565 24640 24662 I Unity   : Product: 'it.megasoft78.wordsjungle.small_pack_coins',
11-08 17:20:37.565 24640 24662 I Unity   : PurchaseFailureReason: UserCancelled`

**Comment by Trinkes** [comment]
Can you install [this](https://my.pcloud.com/publink/show?code=XZYnAM7ZMYy6mGwbqOjCqNhQOE0kJk9WkIJk) build and try the payment again?
Don't forget to backup your private key!

**Comment by megasoft78** [comment]
Hi,
yes it's working. :)

**Comment by Trinkes** [comment]
Ok, this fix will roll out on next release.

**Comment by Suriya1991** [comment]
> 

Good day. 
At end of transaction some error occurred please try again message came . Amount is detected.  No paypal receipt or anything.  Diamonds not added to in game account , no credit added in app coins.  What to do?

**Comment by Nyisa123** [comment]
When I buying in app using app coin wallet app the wallet is going to verify page and I can't buy or send to other but I can receive from other.why?
