### ISSUE TITLE
CC required although there are enough APPC and ETH available for the transaction

### ISSUE THREAD

**Issue by nenovmy** [Aptoide/appcoins-wallet-android#112]
1. Make a new wallet and start an app with APPC.
2. Try to buy something -> the CC dialog is opened
3. Add some APPC and ETH to the wallet
3. Open the app and try to buy the same thing ->

expected: The price is shown in APPC and you can click buy to pay with APPC
actual: the CC dialog is opened

Tested with:

Unity version: 2018.2.13f1
BDS unity plugin: 0.3
Wallet version: 1.1.1.4

Testing on Samsung galaxy s7 edge with Android 8.0.0

**Comment by Trinkes** [comment]
Hello @nenovmy,
this bug is reported already internally. Expect a fix to be released soon.
