### ISSUE TITLE
In-App crashing

### ISSUE THREAD

**Issue by megasoft78** [Aptoide/appcoins-wallet-android#115]
Hi,
in one of my wallet I'm getting a crash that close my game.
Here's the logcat:
`11-08 10:24:38.557  8989  9042 D HTTP_TRACE: <---------------------------BEGIN REQUEST---------------------------------->
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: Request encoded url: GET https://api.trustwalletapp.com/prices?currency=USD&&symbols=ETH
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: Request decoded url: GET https://api.trustwalletapp.com/prices?currency=USD&&symbols=ETH
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: =============== Headers ===============
11-08 10:24:38.557  8989  9042 D HTTP_TRACE:
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: =============== END Headers ===============
11-08 10:24:38.557  8989  9042 D HTTP_TRACE:
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: Response timeout: 260ms
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: Response message:
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: Response code: 200
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: Response body:
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: {"status":true,"response":[{"id":"ethereum","name":"Ethereum","symbol":"ETH","price":"214.436583851","percent_change_24h":"-2.54","image":"https://files.coinmarketcap.com/static/img/coins/128x128/ethereum.png"}]}
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: =============== Headers ===============
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: cf-ray : 4766fcdb8ab43dd1-MXP
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: server : cloudflare
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: expect-ct : max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: via : 1.1 vegur
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: vary : Accept-Encoding
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: etag : W/"d4-pp7HQY5VYq+VGjvpT4jToIEueKU"
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: access-control-allow-origin : *
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: x-powered-by : Express
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: set-cookie : __cfduid=da65076feafedbc06f2d2c5ac4d6fffe71541669078; expires=Fri, 08-Nov-19 09:24:38 GMT; path=/; domain=.trustwalletapp.com; HttpOnly; Secure
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: content-type : application/json; charset=utf-8
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: date : Thu, 08 Nov 2018 09:24:38 GMT
11-08 10:24:38.557  8989  9042 D HTTP_TRACE:
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: =============== END Headers ===============
11-08 10:24:38.557  8989  9042 D HTTP_TRACE:
11-08 10:24:38.557  8989  9042 D HTTP_TRACE: <-----------------------------END REQUEST--------------------------------->
11-08 10:24:38.557  8989  9042 D HTTP_TRACE:
11-08 10:24:38.557  8989  9042 D HTTP_TRACE:
11-08 10:24:38.565  8989  8989 W System.err: java.lang.RuntimeException: io.reactivex.exceptions.OnErrorNotImplementedException: Cannot resume from PAUSED_CC_PAYMENT status
11-08 10:24:38.565  8989  8989 W System.err:    at com.asfoundation.wallet.App.lambda$setupRxJava$3(App.java:116)
11-08 10:24:38.565  8989  8989 W System.err:    at com.asfoundation.wallet.-$$Lambda$App$jbJJC5ZrE1AO-GbmxmR7s63ueIE.accept(Unknown Source:2)
11-08 10:24:38.565  8989  8989 W System.err:    at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:373)
11-08 10:24:38.565  8989  8989 W System.err:    at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:51)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:73)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.operators.completable.CompletableError.subscribeActual(CompletableError.java:29)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.Completable.subscribe(Completable.java:2171)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.operators.single.SingleZipArray$ZipCoordinator.innerSuccess(SingleZipArray.java:121)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.operators.single.SingleZipArray$ZipSingleObserver.onSuccess(SingleZipArray.java:172)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.Single.subscribe(Single.java:3394)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.operators.single.SingleZipArray$ZipCoordinator.innerSuccess(SingleZipArray.java:121)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.operators.single.SingleZipArray$ZipSingleObserver.onSuccess(SingleZipArray.java:172)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.Single.subscribe(Single.java:3394)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
11-08 10:24:38.566  8989  8989 W System.err:    at io.reactivex.internal.operators.observable.ObservableElementAtSingle$ElementAtObserver.onNext(ObservableElementAtSingle.java:91)
11-08 10:24:38.567  8989  8989 W System.err:    at io.reactivex.internal.operators.mixed.SingleFlatMapObservable$FlatMapObserver.onNext(SingleFlatMapObservable.java:69)
11-08 10:24:38.567  8989  8989 W System.err:    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
11-08 10:24:38.567  8989  8989 W System.err:    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
11-08 10:24:38.567  8989  8989 W System.err:    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
11-08 10:24:38.567  8989  8989 W System.err:    at android.os.Handler.handleCallback(Handler.java:790)
11-08 10:24:38.567  8989  8989 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
11-08 10:24:38.567  8989  8989 W System.err:    at android.os.Looper.loop(Looper.java:164)
11-08 10:24:38.567  8989  8989 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6494)
11-08 10:24:38.567  8989  8989 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
11-08 10:24:38.567  8989  8989 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
11-08 10:24:38.567  8989  8989 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
11-08 10:24:38.567  8989  8989 W System.err: Caused by: io.reactivex.exceptions.OnErrorNotImplementedException: Cannot resume from PAUSED_CC_PAYMENT status
11-08 10:24:38.567  8989  8989 W System.err:    ... 33 more
11-08 10:24:38.568  8989  8989 W System.err: Caused by: java.lang.UnsupportedOperationException: Cannot resume from PAUSED_CC_PAYMENT status
11-08 10:24:38.568  8989  8989 W System.err:    at com.asfoundation.wallet.ui.iab.OnChainBuyPresenter.lambda$null$13(OnChainBuyPresenter.java:155)
11-08 10:24:38.568  8989  8989 W System.err:    at com.asfoundation.wallet.ui.iab.-$$Lambda$OnChainBuyPresenter$-J_hj-0lVgORF34_7Ok_9y3nSrM.apply(Unknown Source:15)
11-08 10:24:38.568  8989  8989 W System.err:    at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:83)
11-08 10:24:38.568  8989  8989 W System.err:    ... 26 more
11-08 10:24:38.630  8989  9506 I System.out: Request: Request{method=GET, url=http://52.209.250.255/microraiden/listallchannels?sender=0x47e41a77584a828e37dc0466a6efa75a2eb4ae27&closed=false, tag=null}
11-08 10:24:38.766  8989  9506 I System.out: Response: Response{protocol=http/1.1, code=200, message=OK, url=http://52.209.250.255/microraiden/listallchannels?sender=0x47e41a77584a828e37dc0466a6efa75a2eb4ae27&closed=false}`

**Comment by Trinkes** [comment]
This issue is the same as #111.
