### ISSUE TITLE
My appc are gone

### ISSUE THREAD

**Issue by retro1000000** [Aptoide/appcoins-wallet-android#187]
I used my appc on a game and nothing happens and my appc are gone

**Comment by Trinkes** [comment]
Hello @retro1000000,
What was the game where you spent your coins?

**Comment by retro1000000** [comment]
Era of celestials

**Comment by retro1000000** [comment]
Era of celestials

בתאריך יום ה׳, 20 בדצמ׳ 2018, 18:51, מאת Trinkes <notifications@github.com>:

**Comment by Trinkes** [comment]
Can you send an email to fabio.costa@aptoide.com with your wallet address?

**Comment by Trinkes** [comment]
I was able to confirm that we processed a purchase to that app  on that day, on our side everything worked as expected. Probably that was an error on Era of celestials side. Sorry but o can't help you.
