### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by macthesixth** [Aptoide/appcoins-wallet-android#396]
I bought a pack of lord's mobile worth 9.99 dollars through appwallet one month ago, but due to some problem in appwallet it didn't reach to lord's mobile. Lord's mobile customer service has confirmed me that the money has been stuck in Appcoins wallet. Please refund the amount.
![Screenshot_2019-07-18-20-14-41-77](https://user-images.githubusercontent.com/53319670/62511249-5bd2e680-b830-11e9-9e0c-ce0f103bf1ce.png)

**Comment by JoaoRaimundo** [comment]
Can you please provide us your wallet address by sending an email to joao.raimundo@aptoide.com
