### ISSUE TITLE
double spending in app purchase?

### ISSUE THREAD

**Issue by alex8819** [Aptoide/appcoins-wallet-android#44]
I have a question, I spent 21 appc for become pro in an app

-First I transfer 50 appc
-Second I transfer 0.01 ETH
-Third I spend 21 appc for become Pro in and Aptoide app

Now the appcoin wallet say that I have 29 appc, but the history say that I spend 42 appc for the app

When I have to spend only 21

**Comment by Trinkes** [comment]
Hello @alex8819,
Can you reproduce the issue with the latest release?
